name: Direct Deploy to Azure Web App - MarufTestApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create deployment folder excluding unwanted dirs
        run: |
          mkdir deploy_package
          rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' . deploy_package/

      - name: Zip deployment package
        run: |
          cd deploy_package
          zip -r ../release.zip .
          cd ..

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: full-app-package
          path: release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MarufTestApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8996A5A587E94E05934DC038DE1FC4B2 }}
          package: release.zip
